service: serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}

custom: 
  tableName: Users

functions:
  hello:
    handler: handler.helloWorld
    events:
      - httpApi:
          path: /
          method: get
  getAllUsers:
    handler: handler.getAllUsers
    events:
      - httpApi:
          path: /users
          method: get
  getUser:
    handler: handler.getUser
    events:
      - httpApi:
          path: /users/{id}
          method: get
  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /user
          method: post
  updateUser:
    handler: handler.updateUser
    events:
      - httpApi:
          path: /user/{id}
          method: put
  removeUser:
    handler: handler.removeUser
    events:
      - httpApi:
          path: /user/{id}
          method: delete
  
plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1            