service: serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}

functions:
  hello:
    handler: handler.helloWorld
    events:
      - httpApi:
          path: /
          method: get
  get:
    handler: handler.get
    events:
      - httpApi:
          path: /get
          method: get
  post:
    handler: handler.post
    events:
      - httpApi:
          path: /post
          method: post
  put:
    handler: handler.put
    events:
      - httpApi:
          path: /put
          method: put
  delete:
    handler: handler.remove
    events:
      - httpApi:
          path: /delete
          method: delete
  
plugins:
  - serverless-plugin-typescript